[package]
name = "sorter"
version = "0.1.0"
edition = "2024"

[dependencies]
unicode-segmentation = "1.10"
rayon = "1.5"
num_cpus = "1.16"
fxhash = "0.2"

[profile.release]
opt-level = 3
overflow-checks = false
strip = "symbols"